import os
import uuid

from google.adk import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai.types import Content, Part

from app.core.config import settings
from app.core.database import SessionLocal
from app.agents.analytics_agent import run_analytics_agent
from app.agents.planner_agent import run_planner_agent
from app.agents.rescheduler_agent import run_rescheduler_agent

# Inject Gemini API Key into environment variables for ADK/Gemini client
if settings.GEMINI_API_KEY:
    os.environ["GEMINI_API_KEY"] = settings.GEMINI_API_KEY


async def run_orchestrator_agent(user_id: uuid.UUID, user_message: str) -> str:
    """
    Creates and executes the ADK 2.0 Conversational Orchestrator Agent.
    Routes queries to the appropriate sub-agents (Analytics, Planner, Rescheduler)
    or handles general conversation directly.
    """

    # Tool 1: Route to Analytics Coach
    async def delegate_to_analytics_coach(query: str) -> str:
        """
        Invokes the Analytics Coach Agent to analyze productivity patterns, task statistics,
        completion rates, and reschedule count logs.
        
        Args:
            query: The specific question or prompt about performance or metrics.
        """
        async with SessionLocal() as session:
            return await run_analytics_agent(
                db=session,
                user_id=user_id,
                user_message=query
            )

    # Tool 2: Route to Task Planner
    async def delegate_to_task_planner(query: str) -> str:
        """
        Invokes the Task Planner Agent to create new categories and scaffold new tasks
        based on the user's goals or projects.
        
        Args:
            query: The planning prompt describing the goal or project.
        """
        return await run_planner_agent(
            user_id=user_id,
            user_message=query
        )

    # Tool 3: Route to Schedule Optimizer (Rescheduler)
    async def delegate_to_rescheduler(query: str) -> str:
        """
        Invokes the Rescheduler Agent to autonomously discover overdue tasks and chronically
        delayed items, then reorganize them into optimized future target dates.
        
        Args:
            query: The prompt requesting rescheduling or optimization.
        """
        return await run_rescheduler_agent(
            user_id=user_id,
            user_message=query
        )

    # 2. Instantiate Orchestrator Agent
    orchestrator_agent = Agent(
        model=settings.GEMINI_MODEL,
        name="conversational_orchestrator",
        instruction=(
            "You are the master AI Productivity Assistant. Your role is to coordinate special productivity sub-agents "
            "to answer the user's requests.\n\n"
            "Rules for tool calling:\n"
            "- If the user asks about stats, trends, streaks, overdue counts, or coaching advice: Call delegate_to_analytics_coach.\n"
            "- If the user wants to plan, split, outline, or organize a new goal/project: Call delegate_to_task_planner.\n"
            "- If the user complains about being overwhelmed, has overdue tasks, or asks to reschedule/optimize their calendar: Call delegate_to_rescheduler.\n"
            "- If the request is a simple greeting, general chit-chat, or a generic question not requiring database tools: Do NOT call any tool, answer the user directly and politely."
        ),
        tools=[delegate_to_analytics_coach, delegate_to_task_planner, delegate_to_rescheduler]
    )

    # 3. Setup InMemory session runner
    session_service = InMemorySessionService()
    runner = Runner(
        agent=orchestrator_agent,
        app_name="task_executor_orchestrator",
        session_service=session_service
    )
    
    user_str = str(user_id)
    session_str = "task_orchestrator_session"
    
    # Create the session context
    await session_service.create_session(
        app_name="task_executor_orchestrator",
        user_id=user_str,
        session_id=session_str
    )
    
    # 4. Stream response
    final_text = ""
    try:
        response_stream = runner.run_async(
            user_id=user_str,
            session_id=session_str,
            new_message=Content(parts=[Part.from_text(text=user_message)])
        )
        
        async for event in response_stream:
            if event.is_final_response() and event.content and event.content.parts:
                final_text += "".join(part.text for part in event.content.parts if part.text)
                
    except Exception as e:
        return f"Error executing conversational orchestrator: {str(e)}"
        
    return final_text or "No response generated by the orchestrator."
